#!/usr/bin/env python
# -*- coding: utf-8 -*-

#IDs:
empty_view_id = "empty_view"
geraetetyp_view_id = "geraetetyp_view"

ADDON = "addon"
PARENT = "parent"
CLIENT = "client"
DID = "did"
GID = "gid"
DEVICE = "device"
LOCAL_FAVS = "local_favs"
SCENE_ID = "scene_id"
PREVIOUS_LIST_POSITION = "previous_list_position"
POSITION = "position"
ICONSETKEY = "iconsetKey"
ICON_SET_INVERTED = "iconSetInverted"
DEVICE_GROUP = "deviceGroup"
USE_LOCAL_FAVORITES = "use_local_favorites"
SLIDER = "slider"
STATUS = "status"
TITLE = "title"
ICON = "icon"
UP = "up"
DOWN = "down"
AUTO = "auto"
GROUP = "group"
RADIO = "radio"
ON = "on"
OFF = "off"
SID = "sid"
NAME = "name"
DESCRIPTION = "description"
IS_EXECUTABLE = "isExecutable"
SYNC = "sync"
GROUPS = "groups"
ACTIONS = "actions"
PROPERTIES = "properties"
IS_ACTIVE = "isActive"
FAVORED_ID = "favoredId"
AVAIL = "avail"
HAS_ERRORS = "hasErrors"
AUTOMATED = "automated"
TYPE = "type"
ICONSET_INVERTED = "iconsetInverted"
CMID = "cmdId"
PARAM = "param"
ICONSET = "iconset"
PERCENT_TYPE = "PERCENT"
DEGREE_TYPE = "DEGREE"
NOTHING = "NOTHING"
UPDATE = "UPDATE"
UPDATE_SENT = "UPDATE_SENT"

ACTION_ANALOG_FORWARD = 113
ACTION_ANALOG_MOVE = 49
ACTION_ANALOG_MOVE_X = 601
ACTION_ANALOG_MOVE_Y = 602
ACTION_ANALOG_REWIND = 114
ACTION_ANALOG_SEEK_BACK = 125
ACTION_ANALOG_SEEK_FORWARD = 124
ACTION_ASPECT_RATIO = 19
ACTION_AUDIO_DELAY = 161
ACTION_AUDIO_DELAY_MIN = 54
ACTION_AUDIO_DELAY_PLUS = 55
ACTION_AUDIO_NEXT_LANGUAGE = 56
ACTION_BACKSPACE = 110
ACTION_BIG_STEP_BACK = 23
ACTION_BIG_STEP_FORWARD = 22
ACTION_BUILT_IN_FUNCTION = 122
ACTION_CALIBRATE_RESET = 48
ACTION_CALIBRATE_SWAP_ARROWS = 47
ACTION_CHANGE_RESOLUTION = 57
ACTION_CHANNEL_DOWN = 185
ACTION_CHANNEL_SWITCH = 183
ACTION_CHANNEL_UP = 184
ACTION_CHAPTER_OR_BIG_STEP_BACK = 98
ACTION_CHAPTER_OR_BIG_STEP_FORWARD = 97
ACTION_CONTEXT_MENU = 117
ACTION_COPY_ITEM = 81
ACTION_CREATE_BOOKMARK = 96
ACTION_CREATE_EPISODE_BOOKMARK = 95
ACTION_CURSOR_LEFT = 120
ACTION_CURSOR_RIGHT = 121
ACTION_CYCLE_SUBTITLE = 99
ACTION_DECREASE_PAR = 220
ACTION_DECREASE_RATING = 137
ACTION_DELETE_ITEM = 80
ACTION_ENTER = 135
ACTION_ERROR = 998
ACTION_FILTER = 233
ACTION_FILTER_CLEAR = 150
ACTION_FILTER_SMS2 = 151
ACTION_FILTER_SMS3 = 152
ACTION_FILTER_SMS4 = 153
ACTION_FILTER_SMS5 = 154
ACTION_FILTER_SMS6 = 155
ACTION_FILTER_SMS7 = 156
ACTION_FILTER_SMS8 = 157
ACTION_FILTER_SMS9 = 158
ACTION_FIRST_PAGE = 159
ACTION_FORWARD = 16
ACTION_GESTURE_BEGIN = 501
ACTION_GESTURE_END = 599
ACTION_GESTURE_NOTIFY = 500
ACTION_GESTURE_PAN = 504
ACTION_GESTURE_ROTATE = 503
ACTION_GESTURE_SWIPE_DOWN = 541
ACTION_GESTURE_SWIPE_DOWN_TEN = 550
ACTION_GESTURE_SWIPE_LEFT = 511
ACTION_GESTURE_SWIPE_LEFT_TEN = 520
ACTION_GESTURE_SWIPE_RIGHT = 521
ACTION_GESTURE_SWIPE_RIGHT_TEN = 530
ACTION_GESTURE_SWIPE_UP = 531
ACTION_GESTURE_SWIPE_UP_TEN = 540
ACTION_GESTURE_ZOOM = 502
ACTION_GUIPROFILE_BEGIN = 204
ACTION_HIGHLIGHT_ITEM = 8
ACTION_INCREASE_PAR = 219
ACTION_INCREASE_RATING = 136
ACTION_INPUT_TEXT = 244
ACTION_JUMP_SMS2 = 142
ACTION_JUMP_SMS3 = 143
ACTION_JUMP_SMS4 = 144
ACTION_JUMP_SMS5 = 145
ACTION_JUMP_SMS6 = 146
ACTION_JUMP_SMS7 = 147
ACTION_JUMP_SMS8 = 148
ACTION_JUMP_SMS9 = 149
ACTION_LAST_PAGE = 160
ACTION_MOUSE_DOUBLE_CLICK = 103
ACTION_MOUSE_DRAG = 106
ACTION_MOUSE_END = 109
ACTION_MOUSE_LEFT_CLICK = 100
ACTION_MOUSE_LONG_CLICK = 108
ACTION_MOUSE_MIDDLE_CLICK = 102
ACTION_MOUSE_MOVE = 107
ACTION_MOUSE_RIGHT_CLICK = 101
ACTION_MOUSE_START = 100
ACTION_MOUSE_WHEEL_DOWN = 105
ACTION_MOUSE_WHEEL_UP = 104
ACTION_MOVE_DOWN = 4
ACTION_MOVE_ITEM = 82
ACTION_MOVE_ITEM_DOWN = 116
ACTION_MOVE_ITEM_UP = 115
ACTION_MOVE_LEFT = 1
ACTION_MOVE_RIGHT = 2
ACTION_MOVE_UP = 3
ACTION_MUTE = 91
ACTION_NAV_BACK = 92
ACTION_NEXT_CHANNELGROUP = 186
ACTION_NEXT_CONTROL = 181
ACTION_NEXT_ITEM = 14
ACTION_NEXT_LETTER = 140
ACTION_NEXT_PICTURE = 28
ACTION_NEXT_SCENE = 138
ACTION_NEXT_SUBTITLE = 26
ACTION_NONE = 0
ACTION_NOOP = 999
ACTION_OSD_HIDESUBMENU = 84
ACTION_OSD_SHOW_DOWN = 72
ACTION_OSD_SHOW_LEFT = 69
ACTION_OSD_SHOW_RIGHT = 70
ACTION_OSD_SHOW_SELECT = 73
ACTION_OSD_SHOW_UP = 71
ACTION_OSD_SHOW_VALUE_MIN = 75
ACTION_OSD_SHOW_VALUE_PLUS = 74
ACTION_PAGE_DOWN = 6
ACTION_PAGE_UP = 5
ACTION_PARENT_DIR = 9
ACTION_PASTE = 180
ACTION_PAUSE = 12
ACTION_PLAY = 68
ACTION_PLAYER_FORWARD = 77
ACTION_PLAYER_PLAY = 79
ACTION_PLAYER_PLAYPAUSE = 229
ACTION_PLAYER_REWIND = 78
ACTION_PREVIOUS_CHANNELGROUP = 187
ACTION_PREVIOUS_MENU = 10
ACTION_PREV_CONTROL = 182
ACTION_PREV_ITEM = 15
ACTION_PREV_LETTER = 141
ACTION_PREV_PICTURE = 29
ACTION_PREV_SCENE = 139
ACTION_PVR_PLAY = 188
ACTION_PVR_PLAY_RADIO = 190
ACTION_PVR_PLAY_TV = 189
ACTION_QUEUE_ITEM = 34
ACTION_RECORD = 170
ACTION_RELOAD_KEYMAPS = 203
ACTION_REMOVE_ITEM = 35
ACTION_RENAME_ITEM = 87
ACTION_REWIND = 17
ACTION_ROTATE_PICTURE_CCW = 51
ACTION_ROTATE_PICTURE_CW = 50
ACTION_SCAN_ITEM = 201
ACTION_SCROLL_DOWN = 112
ACTION_SCROLL_UP = 111
ACTION_SELECT_ITEM = 7
ACTION_SETTINGS_LEVEL_CHANGE = 242
ACTION_SETTINGS_RESET = 241
ACTION_SHIFT = 118
ACTION_SHOW_CODEC = 27
ACTION_SHOW_FULLSCREEN = 36
ACTION_SHOW_GUI = 18
ACTION_SHOW_INFO = 11
ACTION_SHOW_MPLAYER_OSD = 83
ACTION_SHOW_OSD = 24
ACTION_SHOW_OSD_TIME = 123
ACTION_SHOW_PLAYLIST = 33
ACTION_SHOW_SUBTITLES = 25
ACTION_SHOW_VIDEOMENU = 134
ACTION_SMALL_STEP_BACK = 76
ACTION_STEP_BACK = 21
ACTION_STEP_FORWARD = 20
ACTION_STEREOMODE_NEXT = 235
ACTION_STEREOMODE_PREVIOUS = 236
ACTION_STEREOMODE_SELECT = 238
ACTION_STEREOMODE_SET = 240
ACTION_STEREOMODE_TOGGLE = 237
ACTION_STEREOMODE_TOMONO = 239
ACTION_STOP = 13
ACTION_SUBTITLE_ALIGN = 232
ACTION_SUBTITLE_DELAY = 162
ACTION_SUBTITLE_DELAY_MIN = 52
ACTION_SUBTITLE_DELAY_PLUS = 53
ACTION_SUBTITLE_VSHIFT_DOWN = 231
ACTION_SUBTITLE_VSHIFT_UP = 230
ACTION_SWITCH_PLAYER = 234
ACTION_SYMBOLS = 119
ACTION_TAKE_SCREENSHOT = 85
ACTION_TELETEXT_BLUE = 218
ACTION_TELETEXT_GREEN = 216
ACTION_TELETEXT_RED = 215
ACTION_TELETEXT_YELLOW = 217
ACTION_TOGGLE_DIGITAL_ANALOG = 202
ACTION_TOGGLE_FULLSCREEN = 199
ACTION_TOGGLE_SOURCE_DEST = 32
ACTION_TOGGLE_WATCHED = 200
ACTION_TOUCH_LONGPRESS = 411
ACTION_TOUCH_LONGPRESS_TEN = 420
ACTION_TOUCH_TAP = 401
ACTION_TOUCH_TAP_TEN = 410
ACTION_TRIGGER_OSD = 243
ACTION_VIS_PRESET_LOCK = 130
ACTION_VIS_PRESET_NEXT = 128
ACTION_VIS_PRESET_PREV = 129
ACTION_VIS_PRESET_RANDOM = 131
ACTION_VIS_PRESET_SHOW = 126
ACTION_VIS_RATE_PRESET_MINUS = 133
ACTION_VIS_RATE_PRESET_PLUS = 132
ACTION_VOLAMP = 90
ACTION_VOLAMP_DOWN = 94
ACTION_VOLAMP_UP = 93
ACTION_VOLUME_DOWN = 89
ACTION_VOLUME_SET = 245
ACTION_VOLUME_UP = 88
ACTION_VSHIFT_DOWN = 228
ACTION_VSHIFT_UP = 227
ACTION_ZOOM_IN = 31
ACTION_ZOOM_LEVEL_1 = 38
ACTION_ZOOM_LEVEL_2 = 39
ACTION_ZOOM_LEVEL_3 = 40
ACTION_ZOOM_LEVEL_4 = 41
ACTION_ZOOM_LEVEL_5 = 42
ACTION_ZOOM_LEVEL_6 = 43
ACTION_ZOOM_LEVEL_7 = 44
ACTION_ZOOM_LEVEL_8 = 45
ACTION_ZOOM_LEVEL_9 = 46
ACTION_ZOOM_LEVEL_NORMAL = 37
ACTION_ZOOM_OUT = 30
ALPHANUM_HIDE_INPUT = 2
CONTROL_TEXT_OFFSET_X = 10
CONTROL_TEXT_OFFSET_Y = 2
ICON_OVERLAY_HD = 6
ICON_OVERLAY_LOCKED = 3
ICON_OVERLAY_NONE = 0
ICON_OVERLAY_RAR = 1
ICON_OVERLAY_UNWATCHED = 4
ICON_OVERLAY_WATCHED = 5
ICON_OVERLAY_ZIP = 2
ICON_TYPE_FILES = 106
ICON_TYPE_MUSIC = 103
ICON_TYPE_NONE = 101
ICON_TYPE_PICTURES = 104
ICON_TYPE_PROGRAMS = 102
ICON_TYPE_SETTINGS = 109
ICON_TYPE_VIDEOS = 105
ICON_TYPE_WEATHER = 107
INPUT_ALPHANUM = 0
INPUT_DATE = 2
INPUT_IPADDRESS = 4
INPUT_NUMERIC = 1
INPUT_PASSWORD = 5
INPUT_TIME = 3
KEY_APPCOMMAND = 53248
KEY_ASCII = 61696
KEY_BUTTON_A = 256
KEY_BUTTON_B = 257
KEY_BUTTON_BACK = 275
KEY_BUTTON_BLACK = 260
KEY_BUTTON_DPAD_DOWN = 271
KEY_BUTTON_DPAD_LEFT = 272
KEY_BUTTON_DPAD_RIGHT = 273
KEY_BUTTON_DPAD_UP = 270
KEY_BUTTON_LEFT_ANALOG_TRIGGER = 278
KEY_BUTTON_LEFT_THUMB_BUTTON = 276
KEY_BUTTON_LEFT_THUMB_STICK = 264
KEY_BUTTON_LEFT_THUMB_STICK_DOWN = 281
KEY_BUTTON_LEFT_THUMB_STICK_LEFT = 282
KEY_BUTTON_LEFT_THUMB_STICK_RIGHT = 283
KEY_BUTTON_LEFT_THUMB_STICK_UP = 280
KEY_BUTTON_LEFT_TRIGGER = 262
KEY_BUTTON_RIGHT_ANALOG_TRIGGER = 279
KEY_BUTTON_RIGHT_THUMB_BUTTON = 277
KEY_BUTTON_RIGHT_THUMB_STICK = 265
KEY_BUTTON_RIGHT_THUMB_STICK_DOWN = 267
KEY_BUTTON_RIGHT_THUMB_STICK_LEFT = 268
KEY_BUTTON_RIGHT_THUMB_STICK_RIGHT = 269
KEY_BUTTON_RIGHT_THUMB_STICK_UP = 266
KEY_BUTTON_RIGHT_TRIGGER = 263
KEY_BUTTON_START = 274
KEY_BUTTON_WHITE = 261
KEY_BUTTON_X = 258
KEY_BUTTON_Y = 259
KEY_INVALID = 65535
KEY_MOUSE_CLICK = 57344
KEY_MOUSE_DOUBLE_CLICK = 57360
KEY_MOUSE_DRAG = 57604
KEY_MOUSE_DRAG_END = 57606
KEY_MOUSE_DRAG_START = 57605
KEY_MOUSE_END = 61439
KEY_MOUSE_LONG_CLICK = 57376
KEY_MOUSE_MIDDLECLICK = 57346
KEY_MOUSE_MOVE = 57603
KEY_MOUSE_NOOP = 61439
KEY_MOUSE_RDRAG = 57607
KEY_MOUSE_RDRAG_END = 57609
KEY_MOUSE_RDRAG_START = 57608
KEY_MOUSE_RIGHTCLICK = 57345
KEY_MOUSE_START = 57344
KEY_MOUSE_WHEEL_DOWN = 57602
KEY_MOUSE_WHEEL_UP = 57601
KEY_TOUCH = 61440
KEY_UNICODE = 61952
KEY_VKEY = 61440
KEY_VMOUSE = 61439
AID_LEFT = 1
MOVE_RIGHT = 2
AID_RIGHT = 2
AID_UP = 3
AID_DOWN = 4
FOCUS_LIST_DEVICE_GROUP = 4
FOCUS_LIST_SENSORLIST = 5
AID_ENTER = 7
AID_ESC = 10
HP_CEC_ENTER = 11
AID_BACK = 92
FOCUS_LIST_SCENES = 94
FOCUS_LIST_FAV = 95
FOCUS_LIST_DEVICES = 96
FOCUS_LIST_SENSOR = 97
FOCUS_LIST_CONFIG = 98
MOUSE_LEFT_CLICK = 100
SZENEN_DETAILS = 100
FAVORITEN = 101
FAVORITEN_LOKAL = 102
ENTER = 135
HP_CEC_UP = 166
HP_CEC_DOWN = 167
HP_CEC_RIGHT = 168
HP_CEC_LEFT = 169
HP_CEC_BACK = 216
FOCUS_SCROLL_FAVLIST_SCN = 226
FOCUS_LIST_FAVLIST_AKTOREN = 255
FOCUS_LIST_DEVICE_TYP = 257
FOCUS_LIST_SCENE_LIST = 258
FOCUS_SCROLL_SCENELIST = 259
FOCUS_LIST_FAVLIST_SZENEN = 264
FOCUS_SCROLL_FAVLIST_DEV = 993
FOCUS_SCROLL_DEVGROUP = 998
FOCUS_SCROLL_DEVLIST = 999
SENSOREN = 32007
SZENEN = 32005
SZENENTYPEN = 32016
GRUPPEN = 32015
#GERAETE = 32021

ROLLADEN = 32010
SCHALTER = 32011
DIMMER = 32012
THERMOSTATE = 32013
TORE = 32014
ALLE = 32020

SZENEN_MANUELL = 32017
SZENEN_NICHT_MANUELL = 32018
SZENEN_ALLE = 32019

HP_VK_DOWN = 61569
HP_VK_UP = 61568
HP_VK_LEFT = 61570
HP_VK_RIGHT = 61571
HP_VK_ENTER = 61453
HP_VK_BACK = 61448
HP_VK_ESC = 61467


FAVORITEN_VIEW = str(FAVORITEN) + "_view"
FAVORITEN_LOKAL_VIEW = str(FAVORITEN_LOKAL) + "_view"
GERAETETYP_VIEW = "geraetetyp_view"  # String wird so noch irgendwo anders verwendet Anpassung nicht trivial str(GERAETE) + "_view"
DEVICE_GRUPPEN_VIEW = str(GRUPPEN) + "_view"
DEVICE_ALLE_VIEW = str(ALLE) + "_view"
SENSOREN_VIEW = str(SENSOREN) + "_view"
DEVICE_ROLLADEN_VIEW = str(ROLLADEN) + "_view"
DEVICE_SCHALTER_VIEW = str(SCHALTER) + "_view"
DEVICE_DIMMER_VIEW = str(DIMMER) + "_view"
DEVICE_THERMOSTATE_VIEW = str(THERMOSTATE) + "_view"
DEVICE_TORE_VIEW = str(TORE) + "_view"
SZENEN_MANUELL_VIEW = str(SZENEN_MANUELL) + "_view"
SZENEN_NICHT_MANUELL_VIEW = str(SZENEN_NICHT_MANUELL) + "_view"
SZENEN_ALLE_VIEW = str(SZENEN_ALLE) + "_view"
SZENENTYP_VIEW = str(SZENENTYPEN) + "_view"
SZENEN_DETAILS_VIEW = str(SZENEN_DETAILS) + "_view"
EMPTY_VIEW = "empty_view"
SZENEN_FOKUS_VIEW = str(FOCUS_LIST_SCENE_LIST) + "_view"
#scene Window



#Homepilot Client
icons = {"iconset1": "aquarium_72_",
         "iconset2": "bargraph_vertikal_72_",
         "iconset4": "deckenlampe_72_",
         "iconset5": "ein_aus_schalter1_72_",
         "iconset6": "jalousie_72_",
         "iconset7": "markise_72_",
         "iconset8": "rollladen1_72_",
         "iconset9": "schiebetuer_72_",
         "iconset10": "steckdose_72_",
         "iconset11": "tischlampe_72_",
         "iconset12": "tuer_72_",
         "iconset13": "stehlampe_72_",
         "iconset14": "schiebeladen_72_",
         "iconset15": "rollladen2_72_",
         "iconset16": "pumpe_72_",
         "iconset17": "kaffeemaschine_72_",
         "iconset18": "gartensprenkler_72_",
         "iconset20": "sunscreen_72_",
         "iconset21": "birne1_72_",
         "iconset22": "bargraph_horizontal_72_",
         "iconset23": "bewegungsmelder_72_",
         "iconset24": "fenster_72_",
         "iconset25": "genericsensor_72_",
         "iconset26": "rauchmelder_72_",
         "iconset27": "schliesskontakt_72_",
         "iconset28": "thermostat_72_",
         "iconset30": "garage_72_",
         "iconset31": "sektionaltor_72_",
         "iconset32": "lichterkette_72_",
         "iconset33": "weihnachtsbaum_72_",
         "iconset34": "dachfenster_72_",
         "iconset35": "handsender_72_",
         "iconset36": "leinwand_72_",
         "iconset37": "radio_72_",
         "iconset38": "smartphone_72_",
         "iconset39": "ventilator_72_"}

DAWN = "dawn"
DUSK = "dusk"
TIME = "time"
WIND = "wind"
TEMPERATUR = "temperature"
TEMPERATOR = "temperator"
GENERIC = "generic"
TRIGGER = "trigger"
CLOSINGCONTACT = "closingContact"
SMOKE = "smoke"
SUN = "sun"
MANUAL = "manual"
DUST = "dust"
FAVORED = "favored"
SMARTPHONE = "smartphone"
MOTION = "motion"
WARNING = "warning"
RAIN = "rain"

DEVICESET = [DEVICE_ROLLADEN_VIEW, DEVICE_SCHALTER_VIEW,
             DEVICE_DIMMER_VIEW, DEVICE_THERMOSTATE_VIEW,
             DEVICE_TORE_VIEW, DEVICE_ALLE_VIEW]
SCENE_SET = [SZENEN_MANUELL_VIEW, SZENEN_NICHT_MANUELL_VIEW,
             SZENEN_ALLE_VIEW]
SHUTDOWN_SET = [FOCUS_LIST_FAV, FOCUS_LIST_DEVICES, FOCUS_LIST_SCENES, FOCUS_LIST_SENSOR, FOCUS_LIST_CONFIG]

SCROLLBAR_IDS = [FOCUS_LIST_FAVLIST_AKTOREN, FOCUS_LIST_FAVLIST_SZENEN, FOCUS_LIST_DEVICE_GROUP]